In [1]:
# My first python program
print ('Hello World')

Hello World


In [3]:
# My second program
print ("\n My second program\t is this ")


 My second program	 is this 


In [10]:
# Sample program with variables
my_first_var = " Gracy "
print ( "My Name is ")
print (my_first_var.upper())
print (my_first_var.lower())
print (my_first_var.title())
my_first_var.lower?

My Name is 
 GRACY 
 gracy 
 Gracy 


In [9]:
my_frist_var.lower?


Object `my_frist_var.lower` not found.


In [3]:
x=1
y=2
#x+y
print ( x+y)

3


In [4]:
def add_numbers(x+y)
    return x+y

SyntaxError: invalid syntax (<ipython-input-4-cb878f1362a8>, line 1)

In [6]:
def add_numbers(x,y):
    return x+y

In [7]:
add_numbers(3,4)

7

In [9]:
def add_numbers(x,y,z=None):
    if ( z == None):
        return x+y
    else:
        return x+y+z

In [11]:
add_numbers(2,4)

6

In [12]:
add_numbers(2,3,4)

9

In [17]:
def add_num(x,y,z=None,Flag=False):
    if (Flag):
        print "Flag is true"
    else:
        print "Flag is False"
    if ( z == None ):
            print x+y
    else:
            print x+y+z
            

In [18]:
add_num(1,2,3)

Flag is False
6


In [19]:
type('Its a string')

str

In [20]:
type ("Its what")

str

In [21]:
type (10)

int

In [22]:
type (10.0)

float

In [23]:
type (100.00000)

float

In [24]:
type(None)

NoneType

In [25]:
type(add_num)

function

In [26]:
x = (1,'a',2,'b')
type (x)

tuple

In [27]:
x.insert(10)

AttributeError: 'tuple' object has no attribute 'insert'

In [28]:
x.add(10)

AttributeError: 'tuple' object has no attribute 'add'

In [29]:
x=[1,2,3,'a']

In [30]:
type(x)

list

In [31]:
x.append(4)

In [32]:
print x


[1, 2, 3, 'a', 4]


In [34]:
for item in x:
    print(item)

1
2
3
a
4


In [35]:
len(X)

NameError: name 'X' is not defined

In [36]:
len(x)

5

In [41]:
x = [1,2,3,4,'a','b']
i=0 
while ( i != len(x)):
    print (x[i])
    i = i+1

1
2
3
4
a
b


In [42]:
print (x)

[1, 2, 3, 4, 'a', 'b']


In [43]:
y = [5,6,7,8]

In [44]:
print (x+y)

[1, 2, 3, 4, 'a', 'b', 5, 6, 7, 8]


In [45]:
print (x*3)

[1, 2, 3, 4, 'a', 'b', 1, 2, 3, 4, 'a', 'b', 1, 2, 3, 4, 'a', 'b']


In [46]:
print (1 in x)

True


In [47]:
1 in x


True

In [48]:
x= 'this is a string'
print (x)

this is a string


In [49]:
print (x[0])

t


In [50]:
print (x[0:1])

t


In [52]:
print (x[0:6])

this i


In [53]:
print (x[-1])
#This will return the last element of the string.

g


In [54]:
#This will return the slice starting from the 4th element from the end and stopping before the 2nd element from the end.
print (x[-4:-2])

ri


In [55]:
#his is a slice from the beginning of the string and stopping before the 3rd element.
x[:3]

'thi'

In [56]:
#And this is a slice starting from the 4th element of the string and going all the way to the end.'
x[3:]

's is a string'

In [57]:
fn = "Gnana"
ln = "Gracy"
print(fn + ' ' + ln)


Gnana Gracy


In [58]:

print(fn*3)

GnanaGnanaGnana


In [59]:
print (G in fn)

NameError: name 'G' is not defined

In [60]:
print ('G' in fn)

True


In [61]:
#split returns a list of all the words in a string, or a list split on a specific character.
firstname = 'Christopher Arthur Hansen Brooks'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Christopher Arthur Hansen Brooks'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

Christopher
Brooks


In [62]:
#Make sure you convert objects to strings before concatenating.
print('chris' + 2)


TypeError: cannot concatenate 'str' and 'int' objects

In [1]:
print ('chris' + str(2))

chris2


In [19]:
#Dictionaries associate keys with values.
x = {'apple':0,'mango':1}
print(x['apple'])
for fruits in x:
    print(fruits)
x['orange'] = 2
for fruits in x:
    print(fruits)
for val in x.values():
    print (val)
    
for fruits,val in x.items():
    print fruits 
    print val

0
mango
apple
orange
mango
apple
2
1
0
orange
2
mango
1
apple
0


In [22]:
x=('chris','Gracy','gracy@.com')
fname , lname , email = x
print(fname)
print(lname)
print(email)

chris
Gracy
gracy@.com


In [23]:
#Python has a built in method for convenient string formatting.

sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))


Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


In [24]:
#Reading and Writing CSV files
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3] # The first three dictionaries in our list.


[{None: ['1989'],
  'class': '1',
  'cty': 'cbe',
  'cyl': '3',
  'displ': '5',
  'drv': 'f',
  'fl': 'e',
  'hwy': '50',
  'manufacturer': 'maruthi',
  'model': 'eco',
  'mpg': '120',
  'trans': '4',
  'year': '1'},
 {None: ['1979'],
  'class': '2',
  'cty': 'chn',
  'cyl': '4',
  'displ': '5',
  'drv': 'f',
  'fl': 'e',
  'hwy': '60',
  'manufacturer': 'hyndai',
  'model': 'i10',
  'mpg': '130',
  'trans': '4',
  'year': '5'}]

In [26]:
import csv
%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[0:]

[{None: ['1989'],
  'class': '1',
  'cty': 'cbe',
  'cyl': '3',
  'displ': '5',
  'drv': 'f',
  'fl': 'e',
  'hwy': '50',
  'manufacturer': 'maruthi',
  'model': 'eco',
  'mpg': '120',
  'trans': '4',
  'year': '1'},
 {None: ['1979'],
  'class': '2',
  'cty': 'chn',
  'cyl': '4',
  'displ': '5',
  'drv': 'f',
  'fl': 'e',
  'hwy': '60',
  'manufacturer': 'hyndai',
  'model': 'i10',
  'mpg': '130',
  'trans': '4',
  'year': '5'}]

In [27]:
len(mpg)

2

In [28]:
#csv.Dictreader has read in each row of our csv file as a dictionary. len shows that our list is comprised of 234 dictionaries.
#keys gives us the column names of our csv.
mpg[0].keys()

['mpg',
 'trans',
 'displ',
 'year',
 'cty',
 'drv',
 None,
 'hwy',
 'model',
 'manufacturer',
 'fl',
 'class',
 'cyl']

In [31]:
#This is how to find the average cty fuel economy across all cars. All values in the dictionaries are strings, so we need to convert to float.

sum(float(d['hwy']) for d in mpg) / len(mpg)


#Similarly this is how to find the average hwy fuel economy across all cars.

#sum(float(d['hwy']) for d in mpg) / len(mpg)


#Use set to return the unique values for the number of cylinders the cars in our dataset have.

cylinders = set(d['cyl'] for d in mpg)

cylinders

{'3', '4'}

In [36]:
#Here's a more complex example where we are grouping the cars by number of cylinder, and finding the average cty mpg for each group.

CtyMpgByCyl = []


for c in cylinders: # iterate over all the cylinder levels

    summpg = 0

    cyltypecount = 0

    for d in mpg: # iterate over all dictionaries

        if d['cyl'] == c: # if the cylinder level type matches,

            summpg += float(d['hwy']) # add the cty mpg

            cyltypecount += 1 # increment the count

    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')


CtyMpgByCyl.sort(key=lambda x: x[0])

CtyMpgByCyl


#Use set to return the unique values for the class types in our dataset.

#vehicleclass = set(d['class'] for d in mpg) # what are the class types

#vehicleclass

[('3', 50.00), ('4', 60.00)]

In [37]:
#And here's an example of how to find the average hwy mpg for each class of vehicle in our dataset.

HwyMpgByClass = []


for t in vehicleclass: # iterate over all the vehicle classes

    summpg = 0

    vclasscount = 0

    for d in mpg: # iterate over all dictionaries

        if d['class'] == t: # if the cylinder amount type matches,

            summpg += float(d['hwy']) # add the hwy mpg

            vclasscount += 1 # increment the count

    HwyMpgByClass.append((t, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')



HwyMpgByClass.sort(key=lambda x: x[1])

HwyMpgByClass

[('1', 50.00), ('2', 60.00)]

In [39]:
#The Python Programming Language: Dates and Times
import datetime as dt
import time as tm

#time returns the current time in seconds since the Epoch. (January 1st, 1970)
tm.time()dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

#Convert the timestamp to datetime.
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnowdtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

datetime.datetime(2017, 10, 5, 22, 21, 5, 414000)

In [40]:
#Handy datetime attributes:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

(2017, 10, 5, 22, 21, 5)

In [41]:
#timedelta is a duration expressing the difference between two dates.
delta = dt.timedel

ta(days = 100) # create a timedelta of 100 days
delta

datetime.timedelta(100)

In [43]:
today = dt.date.today()

In [44]:
today - delta 

datetime.date(2017, 6, 27)

In [47]:
#The Python Programming Language: Objects and map()
#An example of a class in python:

class Person:
    dept = " Mathematics "
    
    def setname(self,new_name):
        self.name = new_name
    def setloc(self,new_loc):
        self.loc = new_loc
        
person = Person()
person.setname('Ria Danica')
person.setloc('Coimbatore')
print('{} live in {} and works in the department {}'.format(person.name, person.loc, person.dept))

Ria Danica live in Coimbatore and works in the department  Mathematics 


In [50]:
#Here's an example of mapping the min function between two lists.

store1 = [10.00, 11.00, 12.34, 2.34]

store2 = [9.00, 11.10, 12.34, 2.01]

cheapest = map(min, store1, store2)

cheapest


#Now let's iterate through the map object to see the values.

for item in cheapest:

   print(item)

9.0
11.0
12.34
2.01


In [51]:
#The Python Programming Language: Lambda and List Comprehensions



#lambda example
my_func = lambda a,b,c: a+b
my_func(1,2,4)

3

In [52]:
#Let's iterate from 0 to 999 and return the even numbers.
my_lis = []
for num in range ( 0,1000):
    if num % 2 == 0:
        my_lis.append(num)
        
my_lis
        


[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [53]:
#Now the same thing but with list comprehension.

my_list = [number for number in range(0,1000) if number % 2 == 0]

my_list


[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [54]:
#The Python Programming Language: Numerical Python (NumPy)


import numpy as np

my_list = [1,2,3,4,5]
lis = np.array(my_list)
lis

array([1, 2, 3, 4, 5])

In [55]:
#Or just pass in a list directly

y = np.array([4, 5, 6])

y

array([4, 5, 6])

In [56]:
#Pass in a list of lists to create a multidimensional array.

m = np.array([[7, 8, 9], [10, 11, 12]])

m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [57]:
#Use the shape method to find the dimensions of the array. (rows, columns)

m.shape

(2L, 3L)

In [58]:
#arange returns evenly spaced values within a given interval.

n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30

n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [59]:
#reshape returns an array with the same data with a new shape.

n = n.reshape(3, 5) # reshape array to be 3x5

n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [60]:
#linspace returns evenly spaced numbers over a specified interval.

o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4

o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [61]:
#resize changes the shape and size of array in-place.

o.resize(3, 3)

o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [67]:
#ones returns a new array of given shape and type, filled with ones.

np.ones((3, 2))


#zeros returns a new array of given shape and type, filled with zeros.

np.zeros((2, 3))


#eye returns a 2-D array with ones on the diagonal and zeros elsewhere.

np.eye(3)


#diag extracts a diagonal or constructs a diagonal array.

np.diag(y)


#Create an array using repeating list (or see np.tile)

np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [68]:
#Repeat elements of an array using repeat.

np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [69]:
#Combining Arrays

p = np.ones([2, 3], int)

p

array([[1, 1, 1],
       [1, 1, 1]])

In [70]:
#Use vstack to stack arrays in sequence vertically (row wise).

np.vstack([p, 2*p])


#Use hstack to stack arrays in sequence horizontally (column wise).

np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [71]:
x = np.ones([2])
x


array([ 1.,  1.])

In [74]:
y = np.ones([2])
y


array([ 1.,  1.])

In [75]:
x+y

array([ 2.,  2.])

In [76]:
x-y

array([ 0.,  0.])

In [77]:
x*y

array([ 1.,  1.])

In [78]:
x/y

array([ 1.,  1.])

In [79]:
x**2

array([ 1.,  1.])

In [80]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[ 2.  2.]
[ 0.  0.]
[ 1.  1.]
[ 1.  1.]
[ 1.  1.]


In [81]:
#Dot Product:

#[x1 x2 x3]⋅y1y2y3=x1y1+x2y2+x3y3

x.dot(y) # dot product  1*4 + 2*5 + 3*6

2.00

In [83]:
z = np.array([y, y**2])
z
print(len(z)) # number of rows of array

2


In [88]:
#Let's look at transposing arrays. Transposing permutes the dimensions of the array.

z = np.array([y, y**2])

z


#The shape of array z is (2,3) before transposing.

z.shape


#Use .T to get the transpose.

z.T


#The number of rows has swapped with the number of columns.

z.T.shape


#Use .dtype to see the data type of the elements in the array.

z.dtype

dtype('float64')

In [89]:
#Use .astype to cast to a specific type.

z = z.astype('f')

z.dtype

dtype('float32')

In [96]:
#Math Functions

#Numpy has many built in math functions that can be performed on arrays.

a = np.array([-4, -2, 1, 3, 5])
a
a.sum()

a.max()

a.min()

a.mean()

a.std()



3.26

In [98]:
#argmax and argmin return the index of the maximum and minimum values in the array.

a.argmax()

a.argmin()

0

In [99]:
#Indexing / Slicing

s = np.arange(13)**2

s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [100]:
#Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

s[0], s[4], s[-1]

(0, 16, 144)

In [101]:

#Use : to indicate a range. array[start:stop]

#Leaving start or stop empty will default to the beginning/end of the array.

s[1:5]

array([ 1,  4,  9, 16])

In [103]:
#Use negatives to count from the back.

s[-4:]


#A second : can be used to indicate step-size. array[start:stop:stepsize]

#Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

s[-5::-2]

array([64, 36, 16,  4,  0])

In [104]:
#Let's look at a multidimensional array.

r = np.arange(36)

r.resize((6, 6))

r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [105]:
#Use bracket notation to slice: array[row, column]

r[2, 2]

14

In [107]:
#And use : to select a range of rows or columns
r[3,4:7]

array([22, 23])

In [108]:
r[3:7,4:7]

array([[22, 23],
       [28, 29],
       [34, 35]])

In [109]:
r[3:,4:]

array([[22, 23],
       [28, 29],
       [34, 35]])

In [110]:
#Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

r[:2, :-1]


#This is a slice of the last row, and only every other element.

r[-1, ::2]


#We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see np.where)

r[r > 30]

array([31, 32, 33, 34, 35])

In [111]:
#Here we are assigning all values in the array that are greater than 30 to the value of 30.

r[r > 30] = 30

r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [112]:
#Copying Data

#Be careful with copying and modifying arrays in NumPy!

#r2 is a slice of r

r2 = r[:3,:3]

r2


#Set this slice's values to zero ([:] selects the entire array)

r2[:] = 0

r2


#r has also been changed!

r


#To avoid this, use r.copy to create a copy that will not affect the original array

r_copy = r.copy()

r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [113]:
#Now when r_copy is modified, r will not be changed.

r_copy[:] = 10

print(r_copy, '\n')

print(r)

(array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]]), '\n')
[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


In [119]:
#Iterating Over Arrays

#Let's create a new 4 by 3 array of random numbers 0-9.

test = np.random.randint(0, 10, (4,3))

test


#Iterate by row:

for row in test:

   print(row)


#Iterate by index:

for i in range(len(test)):

   print(test[i])


#Iterate by row and index:

for i, row in enumerate(test):

   print('row', i, 'is', row)


#Use zip to iterate over multiple iterables.

test2 = test**2

test2

for i, j in zip(test, test2):

   print(i,'+',j,'=',i+j)

[6 3 1]
[9 1 5]
[5 4 0]
[0 5 9]
[6 3 1]
[9 1 5]
[5 4 0]
[0 5 9]
('row', 0, 'is', array([6, 3, 1]))
('row', 1, 'is', array([9, 1, 5]))
('row', 2, 'is', array([5, 4, 0]))
('row', 3, 'is', array([0, 5, 9]))
(array([6, 3, 1]), '+', array([36,  9,  1]), '=', array([42, 12,  2]))
(array([9, 1, 5]), '+', array([81,  1, 25]), '=', array([90,  2, 30]))
(array([5, 4, 0]), '+', array([25, 16,  0]), '=', array([30, 20,  0]))
(array([0, 5, 9]), '+', array([ 0, 25, 81]), '=', array([ 0, 30, 90]))


In [126]:
#there is a list of all faculty names. Can you write a function and apply it using map to get a list of all facutlry firstname and lastname

names=['Dr.Chris Boris','Dr.Boris Becker','Dr. Punitha Mary']

def name_split(name):
    return name.split(' ')[0] 

result = map(name_split,names)

AttributeError: 'function' object has no attribute 'fn'

NameError: name 'fn' is not defined

In [130]:
names=['Dr.Chris Boris','Dr.Boris Becker','Dr.Punitha Mary']

def name_split(name):
    return name.split(' ')[0] 

result = map(name_split,names)

In [131]:
result


['Dr.Chris', 'Dr.Boris', 'Dr.Punitha']

In [129]:
result


['Dr.Chris', 'Dr.Boris', 'Dr.']

In [132]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    title = person.split()[0]
    lastname = person.split()[-1]
    return '{} {}'.format(title, lastname)

list(map(split_title_and_name, people))


['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

In [133]:
#convert this to lambda
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda person:???))

#option 2
#list(map(split_title_and_name, people)) == list(map(???))

SyntaxError: invalid syntax (<ipython-input-133-a886d1608a36>, line 9)

In [134]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

#option 2
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))

True
True
True
True


True

In [135]:
# convert this to list comprehension
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [lst for lst in range(10) ]



def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [j*i for i in range(10) for j in range(10)]


True

In [136]:
#An organisation has two letter userids which are two letter folowed by two workds (eg. aa49). Our task is to hold a
#record for eacch possible user
# write an initialization line as a single list comprehendsion which creates a lst of all possible user ids
# Assume all are in lower case letter
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

answer = [???]
correct_answer == answer



lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

correct_answer = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]

correct_answer[:50] # Display first 50 ids

SyntaxError: invalid syntax (<ipython-input-136-ce40f2d12220>, line 8)

In [137]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [146]:
old = np.array([[1,2,3],[1,3,3]])
old[0,1:3]


array([2, 3])